# This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id) | No quotes
api_id: 24628750

# Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id) | With quotes
api_hash: api_hash

# Discord Bot Token. Go create a bot on discord. | No quotes
discord_bot_token: discord_bot_t

# Discord Channel ID, may need to enable discord developer mode in settings. | No quotes
discord_channel: discord_c
discord_channel2: discord_c2
# The channels that you'd like to forward messages from. Input telegram channel names here.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  - input_channel
 
input_channel_names2:
  - input_channel2
